steps:
  - name: 'golang:1.24'
    args:
      - go
      - build
      - '-o'
      - main
    id: build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/a-smarter-email-assistant/a-smarter-email-assistant:$SHORT_SHA
      - .
    id: docker-build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/a-smarter-email-assistant/a-smarter-email-assistant:$SHORT_SHA
    id: docker-push
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - a-smarter-email-assistant
      - '--image'
      - >-
        asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/a-smarter-email-assistant/a-smarter-email-assistant:$SHORT_SHA
      - '--region'
      - asia-southeast1
      - '--platform'
      - managed
      - '--allow-unauthenticated'
    id: deploy
images:
  - >-
    asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/a-smarter-email-assistant/a-smarter-email-assistant:$SHORT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
